app = "predictor_togel_bot"
prymary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"
  
[env]
  TELEGRAM_BOT_TOKEN = "7420276710:AAHJ6U2kpDd8ZUP2-yDQOxvc7s_3BwIR4I8"

[http_service]
  internal_port = 8080
