app = "Predictor Togel Bot"
prymary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"
  
[envv]
  TELEGRAM_BOT_TOKEN = "7420276710:AAHJ6U2kpDd8ZUP2-yDQOxvc7s_3BwIR4I8"

[http+service]
  internal_port = 8080
